// Code generated by mockery v2.23.1. DO NOT EDIT.

package battleship_client

import (
	models "battleships/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockBattleshipClient is an autogenerated mock type for the BattleshipClient type
type MockBattleshipClient struct {
	mock.Mock
}

type MockBattleshipClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBattleshipClient) EXPECT() *MockBattleshipClient_Expecter {
	return &MockBattleshipClient_Expecter{mock: &_m.Mock}
}

// AbandonGame provides a mock function with given fields:
func (_m *MockBattleshipClient) AbandonGame() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBattleshipClient_AbandonGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbandonGame'
type MockBattleshipClient_AbandonGame_Call struct {
	*mock.Call
}

// AbandonGame is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) AbandonGame() *MockBattleshipClient_AbandonGame_Call {
	return &MockBattleshipClient_AbandonGame_Call{Call: _e.mock.On("AbandonGame")}
}

func (_c *MockBattleshipClient_AbandonGame_Call) Run(run func()) *MockBattleshipClient_AbandonGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_AbandonGame_Call) Return(_a0 error) *MockBattleshipClient_AbandonGame_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBattleshipClient_AbandonGame_Call) RunAndReturn(run func() error) *MockBattleshipClient_AbandonGame_Call {
	_c.Call.Return(run)
	return _c
}

// Board provides a mock function with given fields:
func (_m *MockBattleshipClient) Board() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBattleshipClient_Board_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Board'
type MockBattleshipClient_Board_Call struct {
	*mock.Call
}

// Board is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) Board() *MockBattleshipClient_Board_Call {
	return &MockBattleshipClient_Board_Call{Call: _e.mock.On("Board")}
}

func (_c *MockBattleshipClient_Board_Call) Run(run func()) *MockBattleshipClient_Board_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_Board_Call) Return(_a0 []string, _a1 error) *MockBattleshipClient_Board_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBattleshipClient_Board_Call) RunAndReturn(run func() ([]string, error)) *MockBattleshipClient_Board_Call {
	_c.Call.Return(run)
	return _c
}

// Description provides a mock function with given fields:
func (_m *MockBattleshipClient) Description() (*models.DescriptionResponse, error) {
	ret := _m.Called()

	var r0 *models.DescriptionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.DescriptionResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.DescriptionResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DescriptionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBattleshipClient_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type MockBattleshipClient_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) Description() *MockBattleshipClient_Description_Call {
	return &MockBattleshipClient_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *MockBattleshipClient_Description_Call) Run(run func()) *MockBattleshipClient_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_Description_Call) Return(_a0 *models.DescriptionResponse, _a1 error) *MockBattleshipClient_Description_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBattleshipClient_Description_Call) RunAndReturn(run func() (*models.DescriptionResponse, error)) *MockBattleshipClient_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Fire provides a mock function with given fields: coords
func (_m *MockBattleshipClient) Fire(coords string) (*models.ShootResult, error) {
	ret := _m.Called(coords)

	var r0 *models.ShootResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.ShootResult, error)); ok {
		return rf(coords)
	}
	if rf, ok := ret.Get(0).(func(string) *models.ShootResult); ok {
		r0 = rf(coords)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ShootResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(coords)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBattleshipClient_Fire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fire'
type MockBattleshipClient_Fire_Call struct {
	*mock.Call
}

// Fire is a helper method to define mock.On call
//   - coords string
func (_e *MockBattleshipClient_Expecter) Fire(coords interface{}) *MockBattleshipClient_Fire_Call {
	return &MockBattleshipClient_Fire_Call{Call: _e.mock.On("Fire", coords)}
}

func (_c *MockBattleshipClient_Fire_Call) Run(run func(coords string)) *MockBattleshipClient_Fire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBattleshipClient_Fire_Call) Return(_a0 *models.ShootResult, _a1 error) *MockBattleshipClient_Fire_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBattleshipClient_Fire_Call) RunAndReturn(run func(string) (*models.ShootResult, error)) *MockBattleshipClient_Fire_Call {
	_c.Call.Return(run)
	return _c
}

// GameStatus provides a mock function with given fields:
func (_m *MockBattleshipClient) GameStatus() (*models.StatusResponse, error) {
	ret := _m.Called()

	var r0 *models.StatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.StatusResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.StatusResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBattleshipClient_GameStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GameStatus'
type MockBattleshipClient_GameStatus_Call struct {
	*mock.Call
}

// GameStatus is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) GameStatus() *MockBattleshipClient_GameStatus_Call {
	return &MockBattleshipClient_GameStatus_Call{Call: _e.mock.On("GameStatus")}
}

func (_c *MockBattleshipClient_GameStatus_Call) Run(run func()) *MockBattleshipClient_GameStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_GameStatus_Call) Return(_a0 *models.StatusResponse, _a1 error) *MockBattleshipClient_GameStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBattleshipClient_GameStatus_Call) RunAndReturn(run func() (*models.StatusResponse, error)) *MockBattleshipClient_GameStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayerStatistic provides a mock function with given fields: nick
func (_m *MockBattleshipClient) GetPlayerStatistic(nick string) (*models.PlayerStatsResponse, error) {
	ret := _m.Called(nick)

	var r0 *models.PlayerStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.PlayerStatsResponse, error)); ok {
		return rf(nick)
	}
	if rf, ok := ret.Get(0).(func(string) *models.PlayerStatsResponse); ok {
		r0 = rf(nick)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nick)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBattleshipClient_GetPlayerStatistic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayerStatistic'
type MockBattleshipClient_GetPlayerStatistic_Call struct {
	*mock.Call
}

// GetPlayerStatistic is a helper method to define mock.On call
//   - nick string
func (_e *MockBattleshipClient_Expecter) GetPlayerStatistic(nick interface{}) *MockBattleshipClient_GetPlayerStatistic_Call {
	return &MockBattleshipClient_GetPlayerStatistic_Call{Call: _e.mock.On("GetPlayerStatistic", nick)}
}

func (_c *MockBattleshipClient_GetPlayerStatistic_Call) Run(run func(nick string)) *MockBattleshipClient_GetPlayerStatistic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBattleshipClient_GetPlayerStatistic_Call) Return(_a0 *models.PlayerStatsResponse, _a1 error) *MockBattleshipClient_GetPlayerStatistic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBattleshipClient_GetPlayerStatistic_Call) RunAndReturn(run func(string) (*models.PlayerStatsResponse, error)) *MockBattleshipClient_GetPlayerStatistic_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayersList provides a mock function with given fields:
func (_m *MockBattleshipClient) GetPlayersList() (*[]models.WaitingPlayerData, error) {
	ret := _m.Called()

	var r0 *[]models.WaitingPlayerData
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]models.WaitingPlayerData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]models.WaitingPlayerData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.WaitingPlayerData)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBattleshipClient_GetPlayersList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayersList'
type MockBattleshipClient_GetPlayersList_Call struct {
	*mock.Call
}

// GetPlayersList is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) GetPlayersList() *MockBattleshipClient_GetPlayersList_Call {
	return &MockBattleshipClient_GetPlayersList_Call{Call: _e.mock.On("GetPlayersList")}
}

func (_c *MockBattleshipClient_GetPlayersList_Call) Run(run func()) *MockBattleshipClient_GetPlayersList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_GetPlayersList_Call) Return(_a0 *[]models.WaitingPlayerData, _a1 error) *MockBattleshipClient_GetPlayersList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBattleshipClient_GetPlayersList_Call) RunAndReturn(run func() (*[]models.WaitingPlayerData, error)) *MockBattleshipClient_GetPlayersList_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatistic provides a mock function with given fields:
func (_m *MockBattleshipClient) GetStatistic() (*models.StatsResponse, error) {
	ret := _m.Called()

	var r0 *models.StatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.StatsResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.StatsResponse); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBattleshipClient_GetStatistic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatistic'
type MockBattleshipClient_GetStatistic_Call struct {
	*mock.Call
}

// GetStatistic is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) GetStatistic() *MockBattleshipClient_GetStatistic_Call {
	return &MockBattleshipClient_GetStatistic_Call{Call: _e.mock.On("GetStatistic")}
}

func (_c *MockBattleshipClient_GetStatistic_Call) Run(run func()) *MockBattleshipClient_GetStatistic_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_GetStatistic_Call) Return(_a0 *models.StatsResponse, _a1 error) *MockBattleshipClient_GetStatistic_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBattleshipClient_GetStatistic_Call) RunAndReturn(run func() (*models.StatsResponse, error)) *MockBattleshipClient_GetStatistic_Call {
	_c.Call.Return(run)
	return _c
}

// GetToken provides a mock function with given fields:
func (_m *MockBattleshipClient) GetToken() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockBattleshipClient_GetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetToken'
type MockBattleshipClient_GetToken_Call struct {
	*mock.Call
}

// GetToken is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) GetToken() *MockBattleshipClient_GetToken_Call {
	return &MockBattleshipClient_GetToken_Call{Call: _e.mock.On("GetToken")}
}

func (_c *MockBattleshipClient_GetToken_Call) Run(run func()) *MockBattleshipClient_GetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_GetToken_Call) Return(_a0 string) *MockBattleshipClient_GetToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBattleshipClient_GetToken_Call) RunAndReturn(run func() string) *MockBattleshipClient_GetToken_Call {
	_c.Call.Return(run)
	return _c
}

// InitGame provides a mock function with given fields: nick, desc, targetNick, coords, wpbot
func (_m *MockBattleshipClient) InitGame(nick string, desc string, targetNick string, coords []string, wpbot bool) error {
	ret := _m.Called(nick, desc, targetNick, coords, wpbot)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, []string, bool) error); ok {
		r0 = rf(nick, desc, targetNick, coords, wpbot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBattleshipClient_InitGame_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitGame'
type MockBattleshipClient_InitGame_Call struct {
	*mock.Call
}

// InitGame is a helper method to define mock.On call
//   - nick string
//   - desc string
//   - targetNick string
//   - coords []string
//   - wpbot bool
func (_e *MockBattleshipClient_Expecter) InitGame(nick interface{}, desc interface{}, targetNick interface{}, coords interface{}, wpbot interface{}) *MockBattleshipClient_InitGame_Call {
	return &MockBattleshipClient_InitGame_Call{Call: _e.mock.On("InitGame", nick, desc, targetNick, coords, wpbot)}
}

func (_c *MockBattleshipClient_InitGame_Call) Run(run func(nick string, desc string, targetNick string, coords []string, wpbot bool)) *MockBattleshipClient_InitGame_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].([]string), args[4].(bool))
	})
	return _c
}

func (_c *MockBattleshipClient_InitGame_Call) Return(_a0 error) *MockBattleshipClient_InitGame_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBattleshipClient_InitGame_Call) RunAndReturn(run func(string, string, string, []string, bool) error) *MockBattleshipClient_InitGame_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshSession provides a mock function with given fields:
func (_m *MockBattleshipClient) RefreshSession() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBattleshipClient_RefreshSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshSession'
type MockBattleshipClient_RefreshSession_Call struct {
	*mock.Call
}

// RefreshSession is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) RefreshSession() *MockBattleshipClient_RefreshSession_Call {
	return &MockBattleshipClient_RefreshSession_Call{Call: _e.mock.On("RefreshSession")}
}

func (_c *MockBattleshipClient_RefreshSession_Call) Run(run func()) *MockBattleshipClient_RefreshSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_RefreshSession_Call) Return(_a0 error) *MockBattleshipClient_RefreshSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBattleshipClient_RefreshSession_Call) RunAndReturn(run func() error) *MockBattleshipClient_RefreshSession_Call {
	_c.Call.Return(run)
	return _c
}

// ResetToken provides a mock function with given fields:
func (_m *MockBattleshipClient) ResetToken() {
	_m.Called()
}

// MockBattleshipClient_ResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetToken'
type MockBattleshipClient_ResetToken_Call struct {
	*mock.Call
}

// ResetToken is a helper method to define mock.On call
func (_e *MockBattleshipClient_Expecter) ResetToken() *MockBattleshipClient_ResetToken_Call {
	return &MockBattleshipClient_ResetToken_Call{Call: _e.mock.On("ResetToken")}
}

func (_c *MockBattleshipClient_ResetToken_Call) Run(run func()) *MockBattleshipClient_ResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBattleshipClient_ResetToken_Call) Return() *MockBattleshipClient_ResetToken_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBattleshipClient_ResetToken_Call) RunAndReturn(run func()) *MockBattleshipClient_ResetToken_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewMockBattleshipClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockBattleshipClient creates a new instance of MockBattleshipClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockBattleshipClient(t mockConstructorTestingTNewMockBattleshipClient) *MockBattleshipClient {
	mock := &MockBattleshipClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
